spring.application.name=eventa-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/eventadb
spring.datasource.username=postgres
spring.datasource.password=JobHunter18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true